name: Update README with current_hi

on:
  schedule:
    - cron: '0 0 * * 1'  # Runs every Monday at 00:00 UTC
  workflow_dispatch:     # Allows you to manually trigger the workflow

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Use any version of Python

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Fetch current_hi value
      run: |
        python get_hi.py > hi_value.txt  # Assuming your Python script outputs the value to a file

    - name: Update README.md
      run: |
        hi_value=$(cat hi_value.txt)
        sed -i "s/<!-- current_hi -->/$hi_value/g" README.md

    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add README.md
        git commit -m "Update current_hi in README"
        git push
