name: Update README with current_hi

on:
  schedule:
    - cron: '0 11 * * *'  # Runs every day at 11:00 AM UTC
  workflow_dispatch:  # Allows you to manually trigger the workflow

jobs:
  update-readme:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write  # Allow write permissions to the repository contents

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Use any version of Python

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Fetch current_hi value
        run: |
          python get_hi.py > hi_value.txt  # Assuming your Python script outputs the value to a file

      - name: Read current_hi value from README.md
        id: read_current_hi
        run: |
          current_hi=$(grep -oP '(?<=<!--HI-->).*?(?=<!--HI-->)' README.md)
          echo "current_hi=$current_hi" >> $GITHUB_ENV

      - name: Update README.md if needed
        run: |
          hi_value=$(cat hi_value.txt)
          if [ "$hi_value" != "$current_hi" ]; then
            sed -i "s/<!--HI-->[^<]*<!--HI-->/$hi_value/g" README.md
            echo "Updated README.md with new current_hi value."
          else
            echo "No change in current_hi value; README.md not updated."
            echo "skip=true" >> $GITHUB_ENV  # Flag to skip commit if no changes
          fi

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          if [ "${{ env.skip }}" != "true" ]; then
            if [ -n "$(git status --porcelain)" ]; then
              git commit -m "Update current_hi in README"
            else
              echo "No changes to commit"
            fi
          else
            echo "Skipping commit as there are no changes to commit."
          fi

      - name: Push changes
        if: success() && env.skip != 'true'
        run: |
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/Ikkimaru/Ikkimaru.git
